### ISSUE TITLE
Exceptions mark exceptional state

### ISSUE THREAD

**Issue by harry-flipkod** [AccordGroup/MandrillSwiftMailer#1]
Thank you very much for your effort.
I don't think the following is a bug but probably intentional coding practice...

The line:
https://github.com/AccordGroup/MandrillSwiftMailer/blob/master/SwiftMailer/MandrillTransport.php#L120

Catches an exception and mutes it. It would be a better practice to at least log the error or rethrow the exception... 
In my case the error was with SSL certificate cURL didn't like but it's still an exceptional state which is supposed to be raised.

**Comment by Kyoushu** [comment]
Thanks for bringing this to our attention. You're right, this could be handled better.

I'm going to take a look at the exceptions thrown by mandrill/mandrill and see which ones can be caught and logged, and which ones should be re-thrown.

https://bitbucket.org/mailchimp/mandrill-api-php/src/da3adc10042eafac2e53de141b358a52b8e53596/src/Mandrill/Exceptions.php?at=master&fileviewer=file-view-default

**Comment by Kyoushu** [comment]
I'm thinking that the try/catch should just be removed.

@Rattler3 your thoughts?

**Comment by jrattue** [comment]
@Kyoushu I agree get rid of it.
