### ISSUE TITLE
SwiftMailer 6.0.x support

### ISSUE THREAD

**Issue by TrashF** [AccordGroup/MandrillSwiftMailer#10]
Your composer.json requires an older version of SwiftMailer. Any plans to support the latest version?

To point out what at least needed to get changed, I created #11. It worked for me and the existing tests are passing, but I don't use much of the features.

**Comment by TrashF** [comment]
And yes, SwiftMailer 6.0.x requires PHP 7.0. I can see that this might be an issue to someone else and a somewhat reasonable reason not to merge my pull request without...well, more preparations 😄

**Comment by jrattue** [comment]
@TrashF We are planning on accepting this, I will merge your request shortly. When reviewing this earlier today I noticed some issues due to the update to swiftmailer, I have been working on resolving these before I merged.

This will require a new 2.0 release that will support only PHP7.
