### ISSUE TITLE
Feature request: Mandrill 'important' field.

### ISSUE THREAD

**Issue by Epskampie** [AccordGroup/MandrillSwiftMailer#16]
Hi, I'd like to request that support for the `important` field from [the send API](https://mandrillapp.com/api/docs/messages.php.html#method=send) be added.

As you mentioned in the README you are open to these kind of requests. If you don't have the manpower however let me know, I'm willing to contribute a pull request if I know it will be accepted.

**Comment by jrattue** [comment]
Hi @Epskampie, if you could open a pull request I am more than happy to review and merge it in. Sorry for not getting back to you sooner.

**Comment by Epskampie** [comment]
Wow, that took a long time for a simple feature. :-) Finally I found some time: #17 

We're still using the 1.x branch, so this PR is for that. I'll make a PR for version 2 after this one is through.

**Comment by jrattue** [comment]
@Epskampie Do you mind writing a test for this?

**Comment by Epskampie** [comment]
@jrattue done!

**Comment by jrattue** [comment]
@Epskampie Merged, thanks for your contribution!

**Comment by Epskampie** [comment]
Thanks! Could you also make a new release in the 1.x branch, so that I can use it via https://packagist.org/packages/accord/mandrill-swiftmailer ?
