### ISSUE TITLE
mandrill/mandrill is abandoned any plans to update to use mailchimp/transactional?

### ISSUE THREAD

**Issue by mambose** [AccordGroup/MandrillSwiftMailer#20]
mandrill/mandrill is abandoned any plans to update to use mailchimp/transactional? Thanks.

https://github.com/craftcms/mandrill/issues/4#issuecomment-866413229

**Comment by Kyoushu** [comment]
Hi @mambose, just a quick bit of background on the situation.

As a result of problems which have arisen during the Covid pandemic, the team which used to support an maintain this library, including myself, no longer work for Accord Marketing. Most of the support and development used to happen during working hours at the company.

We have all moved on to using the `symfony/mailer` mailer component in our new roles.

At the moment I'm not sure if any of the former members have the time to actively maintain this library. I'll get in touch with them to find out for sure, but I expect I'll be flagging this library as `abandoned` on Packagist in the next few days.

**Comment by Kyoushu** [comment]
@mambose If you'd like to submit a PR I'd be happy to review it, otherwise I don't think we'll be actively maintaining this library
