### ISSUE TITLE
Support for templates

### ISSUE THREAD

**Issue by aalaap-ghag** [AccordGroup/MandrillSwiftMailer#7]
Mandrill supports [pre-made templates](https://mandrillapp.com/api/docs/messages.JSON.html#method=send-template), for which there's a different endpoint: `/messages/send-template.json`. It would be nice to have support for this.

**Comment by 506574657220426F656C650D** [comment]
This would indeed be very useful. Any plans on adding it? Or do you accept PR's?

**Comment by jrattue** [comment]
@thePhrenologist Always happy to accept pull requests.
